set -g prefix C-a
unbind C-b
bind C-a send-prefix

#Mouse Support
set -g mouse on

#Enable 256 colors
set -g default-terminal "screen-256color"

# Reload config file
bind r source-file ~/.tmux.conf \; display "Config Reloader!"

#Enable vi  mode for windows
setw -g mode-keys vi

set -s set-clipboard on 

# 设置窗口的初始索引为 1 (Set the base index for windows to 1)
set -g base-index 1
# 设置面板的初始索引为 1 (Set the base index for panes to 1)
setw -g pane-base-index 1

# 将延迟设置为 0
set -s escape-time 0

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'if -F "#{pane_at_left}"   "" "select-pane -L"'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'if -F "#{pane_at_bottom}" "" "select-pane -D"'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'if -F "#{pane_at_top}"    "" "select-pane -U"'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'if -F "#{pane_at_right}"  "" "select-pane -R"'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l


# 水平拆分面板时保持当前路径 (Keep current path when splitting a pane horizontally)
bind '"' split-window -c "#{pane_current_path}"

# 垂直拆分面板时保持当前路径 (Keep current path when splitting a pane vertically)
bind % split-window -h -c "#{pane_current_path}"

