set -g prefix C-a
unbind C-b
bind C-a send-prefix

#Mouse Support
set -g mouse on

#Enable 256 colors
set -g default-terminal "screen-256color"

# Reload config file
bind r source-file ~/.tmux.conf \; display "Config Reloader!"

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

#Enable vi  mode for windows
setw -g mode-keys vi

set -s set-clipboard on 

# 设置窗口的初始索引为 1 (Set the base index for windows to 1)
set -g base-index 1
# 设置面板的初始索引为 1 (Set the base index for panes to 1)
setw -g pane-base-index 1

# 将延迟设置为 0
set -s escape-time 0
